apiVersion: ragme.io/v1
kind: RAGme
metadata:
  name: ragme-sample
  namespace: ragme
spec:
  version: "latest"
  
  images:
    registry: "localhost:5001"
    repository: "ragme"
    tag: "latest"
    pullPolicy: "IfNotPresent"
  
  replicas:
    api: 2
    mcp: 2
    agent: 1
    frontend: 2
  
  storage:
    minio:
      enabled: true
      storageSize: "10Gi"
      accessKey: "minioadmin"
      secretKey: "minioadmin"
    sharedVolume:
      size: "5Gi"
      storageClass: "standard"
  
  vectorDB:
    type: "weaviate"
    weaviate:
      enabled: true
      storageSize: "2Gi"
    milvus:
      enabled: false
  
  resources:
    api:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    mcp:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    frontend:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    agent:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    minio:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    weaviate:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
  
  externalAccess:
    type: "NodePort"
    ingress:
      enabled: false
      host: "ragme.local"
      tlsEnabled: false
  
  authentication:
    oauth:
      google:
        enabled: true
        clientId: "your-google-oauth-client-id"
        clientSecret: "your-google-oauth-client-secret"
        redirectUri: "http://ragme-api:8021/auth/google/callback"
        scope: "openid email profile"
      github:
        enabled: true
        clientId: "your-github-oauth-client-id"
        clientSecret: "your-github-oauth-client-secret"
        redirectUri: "http://ragme-api:8021/auth/github/callback"
        scope: "user:email"
      apple:
        enabled: true
        clientId: "your-apple-oauth-client-id"
        clientSecret: "your-apple-oauth-client-secret"
        redirectUri: "http://ragme-api:8021/auth/apple/callback"
        scope: "name email"
    session:
      secretKey: "ragme-shared-session-secret-key-2025"
      maxAgeSeconds: 86400
      secure: false
      httpOnly: true
      sameSite: "lax"