apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ragme-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ragme.io
  resources:
  - ragmes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ragme.io
  resources:
  - ragmes/finalizers
  verbs:
  - update
- apiGroups:
  - ragme.io
  resources:
  - ragmes/status
  verbs:
  - get
  - patch
  - update