apiVersion: apps/v1
kind: Deployment
metadata:
  name: ragme-weaviate
  namespace: ragme
  labels:
    app: ragme
    component: weaviate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ragme
      component: weaviate
  template:
    metadata:
      labels:
        app: ragme
        component: weaviate
    spec:
      containers:
      - name: weaviate
        image: cr.weaviate.io/semitechnologies/weaviate:1.25.0
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: QUERY_DEFAULTS_LIMIT
          value: "25"
        - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
          value: "true"
        - name: PERSISTENCE_DATA_PATH
          value: "/var/lib/weaviate"
        - name: DEFAULT_VECTORIZER_MODULE
          value: "none"
        - name: ENABLE_MODULES
          value: "text2vec-openai,generative-openai"
        - name: CLUSTER_HOSTNAME
          value: "node1"
        volumeMounts:
        - name: weaviate-data
          mountPath: /var/lib/weaviate
        livenessProbe:
          httpGet:
            path: /v1/.well-known/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /v1/.well-known/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: weaviate-data
        persistentVolumeClaim:
          claimName: ragme-vector-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: ragme-weaviate
  namespace: ragme
  labels:
    app: ragme
    component: weaviate
spec:
  selector:
    app: ragme
    component: weaviate
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: ragme-weaviate-nodeport
  namespace: ragme
  labels:
    app: ragme
    component: weaviate
spec:
  selector:
    app: ragme
    component: weaviate
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort