version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.31.5
    ports:
    - 8080:8080
    - 50051:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
      GRPC_PORT: '50051'
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data: 